name: CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn lint
      - run: yarn prepublish
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn && yarn prepublish
      - run: cd example && yarn && yarn reg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REG_NOTIFY_GITHUB_PLUGIN_CLIENT_ID: ${{ secrets.REG_NOTIFY_GITHUB_PLUGIN_CLIENT_ID }}
